services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: unless-stopped
    ports:
        - "5432:5432"
    environment:
        POSTGRES_USER: user-name
        POSTGRES_PASSWORD: strong-password
    volumes:
        - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
        - "8888:80"
    environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
        - pgadmin-data:/var/lib/pgadmin
        - C:/User/Documents:/var/lib/pgadmin/storage/admin_admin.com/documents

volumes:
    local_pgdata:
    pgadmin-data:
